// This file is part of IzarraVM and is licensed under GNU GPL version 3 only.
// SPDX-License-Identifier: GPL-3.0-only

use izarravm_video::{
    A_SELECT_COLOR1, BIG_DISTIRA_CHIP_NAME, CCA_LOCALSELECT_COLOR0, DACDATA_ADDR_SHIFT, DACDATA_RD,
    DEPTHOP_ALWAYS, DEPTHOP_GREATERTHAN, DEPTHOP_LESSTHAN, DISTIRA_CAPS_VALUE, DISTIRA_ID_VALUE,
    DISTIRA_REG_CAPS, DISTIRA_REG_ID, Distira, DistiraVertex, FBIINIT0_GRAPHICS_RESET,
    FBIINIT1_TILES_IN_X_SHIFT, FBIINIT1_VIDEO_RESET, FBIINIT2_BUFFER_OFFSET_SHIFT, FBIINIT3_REMAP,
    FBZ_CHROMAKEY, FBZ_CLIP_ENABLE, FBZ_DEPTH_BIAS, FBZ_DEPTH_ENABLE, FBZ_DEPTH_OP_SHIFT,
    FBZ_DEPTH_SOURCE, FBZ_DEPTH_WMASK, FBZ_DITHER, FBZ_DRAW_BACK, FBZ_DRAW_FRONT, FBZ_RGB_WMASK,
    FBZ_STIPPLE, FBZ_STIPPLE_PATT, FBZ_W_BUFFER, FBZ_Y_ORIGIN, FBZCP_A_SELECT_SHIFT,
    FBZCP_CC_ADD_CLOCAL, FBZCP_CC_LOCALSELECT_COLOR0, FBZCP_CCA_ADD_SHIFT,
    FBZCP_CCA_LOCALSELECT_SHIFT, FBZCP_TEXTURE_ENABLED, INIT_ENABLE_REMAP, INIT_ENABLE_WRITE,
    LFB_FORMAT_ARGB8888, LFB_FORMAT_DEPTH, LFB_FORMAT_RGB565, LFB_READ_AUX, LFB_READ_FRONT,
    LFB_WRITE_BACK, LFB_WRITE_FRONT, RGB_SELECT_COLOR1, RGB_SELECT_TEXTURE,
    SMALL_DISTIRA_CHIP_NAME, SST_ALPHA_MODE, SST_CHROMA_KEY, SST_CLIP_LEFT_RIGHT,
    SST_CLIP_LOW_Y_HIGH_Y, SST_CLUT_DATA, SST_COLOR0, SST_COLOR1, SST_DAC_DATA, SST_DR_DX,
    SST_DR_DY, SST_DS_DX, SST_DS_DY, SST_DT_DX, SST_DT_DY, SST_DW_DX, SST_DW_DY, SST_FASTFILL_CMD,
    SST_FBI_AFUNC_FAIL, SST_FBI_CHROMA_FAIL, SST_FBI_INIT0, SST_FBI_INIT1, SST_FBI_INIT2,
    SST_FBI_INIT3, SST_FBI_INIT4, SST_FBI_PIXELS_IN, SST_FBI_PIXELS_OUT, SST_FBI_ZFUNC_FAIL,
    SST_FBZ_COLOR_PATH, SST_FBZ_MODE, SST_FDR_DX, SST_FDR_DY, SST_FDZ_DX, SST_FOG_COLOR,
    SST_FOG_MODE, SST_FSTART_B, SST_FSTART_G, SST_FSTART_R, SST_FSTART_Z, SST_FTRIANGLE_CMD,
    SST_FVERTEX_AX, SST_FVERTEX_AY, SST_FVERTEX_BX, SST_FVERTEX_BY, SST_FVERTEX_CX, SST_FVERTEX_CY,
    SST_HV_RETRACE, SST_LFB_MODE, SST_NOP_CMD, SST_START_A, SST_START_B, SST_START_G, SST_START_R,
    SST_START_S, SST_START_T, SST_START_W, SST_START_Z, SST_STATUS, SST_STIPPLE,
    SST_SWAPBUFFER_CMD, SST_TEX_BASE_ADDR, SST_TEXTURE_MODE, SST_TLOD, SST_TRIANGLE_CMD,
    SST_V_RETRACE, SST_VERTEX_AX, SST_VERTEX_AY, SST_VERTEX_BX, SST_VERTEX_BY, SST_VERTEX_CX,
    SST_VERTEX_CY, SST_VIDEO_DIMENSIONS, SST_ZA_COLOR, TEX_R5G6B5, TEXTUREMODE_LOCAL,
};

fn read_reg(distira: &mut Distira, reg: usize) -> u32 {
    (0..4)
        .map(|i| u32::from(distira.read_mmio_u8(reg + i)) << (i * 8))
        .fold(0, |a, b| a | b)
}

fn write_reg(distira: &mut Distira, reg: usize, value: u32) {
    for (i, byte) in value.to_le_bytes().into_iter().enumerate() {
        distira.write_mmio_u8(reg + i, byte);
    }
}

fn red_channel(pixel: u32) -> u32 {
    (pixel >> 16) & 0xff
}

#[path = "distira/device_test.rs"]
mod device;

#[path = "distira/raster_alpha_test.rs"]
mod raster_alpha;

#[path = "distira/color_combine_test.rs"]
mod color_combine;

#[path = "distira/texture_test.rs"]
mod texture;

#[path = "distira/perspective_lod_test.rs"]
mod perspective_lod;

#[path = "distira/ncc_test.rs"]
mod ncc;

#[path = "distira/raster_queue_test.rs"]
mod raster_queue;
