[machine]
cpu = "386"
memory_mib = 16
video = "et4000_ax"

[dos]
c_drive = "R:\\La Colecci\u00f3n by Neville\\dosroot\\"

[audio]
pc_speaker = true
opl3 = true

[audio.sound_blaster]
enabled = true
irq = "5"
dma = "1"
high_dma = "5"

[audio.midi]
backend = "external"
soundfont = ""

[input]
keyboard = true
mouse = true
joystick = true
steam_input = "off"

[diagnostics]
trace_devices = false
